### ISSUE TITLE
Add class to text_field_tag

### ISSUE THREAD

**Issue by tarastrauss** [tarastrauss/chefs_hat#2]
In my HTML document, I'm trying to add a class to a text_field_tag. I think it's just a silly syntax error that I'm getting - but none of the google searches I've done have revealed what that is. I'm not sure if there is something that should be in parenthesis, or if there's something I'm missing syntax-wise. 

![screen shot 2015-11-04 at 2 38 17 pm](https://cloud.githubusercontent.com/assets/14189882/10954396/e773184e-8301-11e5-912a-1521dfec1318.png)

I can add a class to other tags (like the one on line 34) but when I add it to the text_field_tag (on line 30), I'm getting an error.

![screen shot 2015-11-04 at 2 38 05 pm](https://cloud.githubusercontent.com/assets/14189882/10954411/07874a38-8302-11e5-80ef-5dcb9bfc429e.png)

**Comment by tambling** [comment]
Yeah, you need a comma between the name of the `text_field_tag` and any attributes you pass in.

**Comment by tarastrauss** [comment]
I put a comma between there but it just sends 'class: "inline"' into the field. 
![screen shot 2015-11-04 at 2 50 57 pm](https://cloud.githubusercontent.com/assets/14189882/10954642/92aa8138-8303-11e5-8a32-4ecbf0d597f3.png)

I thought 'recipe[name]' is the argument I'm sending through? It works as the argument! When I try to add it as a symbol it doesn't work.

**Comment by tambling** [comment]
Oh! The second argument is the default value. [Observe](http://apidock.com/rails/ActionView/Helpers/FormTagHelper/text_field_tag).

**Comment by tarastrauss** [comment]
Oooooooh. I was actually looking at that page during my google troubleshooting but I didn't understand the second argument/nil thing until you just pointed it out. Thanks!!
